const { User } = require('../models');

// this script generates 150 random profiles with which to seed the database

const userData = [];

const usernameOptions = [
  'shaquilleOatmeal',
  'hangingWithMyGnomies',
  'Leo',
  'Zanny',
  'hoosierDaddy',
  'Willow',
  'Aphrodite',
  'Marz',
  'Trev',
  'Abdo',
  'Abe',
  'fastAndTheCurious',
  'Alex',
  'Alias',
  'Ambro',
  'Ash',
  'averagestudent',
  'Athena',
  'Aus',
  'Ava',
  'BadKarma',
  'googleWasMyIdea',
  'HairyPoppins',
  'FedoraTheExplorah',
  'OPrah',
  'YellowSnowman',
  'JoeNotExotic',
  'UsernameCopied',
  'WhosUrBuddha',
  'UnfinishedSentenc',
  'AllGoodNamesRGone',
  'SomethingSomething',
  'MeForPresident',
  'tinfoilhat',
  'oprahwindfury',
  'anonymouse',
  'DefinitelyNonAthlete',
  'HeartTicker',
  'YesImFunny',
  'BenAfleckIsOK',
  'Magicschoolbus',
  'PawneeGoddess',
  'JeremyBearimy',
  'aDistraction',
  'heyyou',
  'reginaPhalange',
  'IYELLALOT',
  'wilhelmscreamer',
  'laughtilupee',
  'crazyCatLady',
  'bananahammock',
  'thegodfatherpt4',
  'unfriendme',
  'babydoodles',
  'fluffycookie',
  'buhbuhbacon',
  'AshleySaidWhat',
  'LactoseIntolerant',
  'MasterCoder',
  'MasterHacker',
  'Haxx0r',
  'Babushka',
  'YesIVoted',
  'idrinkchocomilk',
  'kentuckycriedchxn',
  'chinchillin',
  'ghostfacekilla',
  'rza',
  'gza',
  'oldirtybastard',
  'bigfootisREAL',
  'nachocheesefries',
  'samwise',
  'frodo',
  'aragorn22',
  'gandalftheWIZORD',
  'boromirlives',
  'brandybuck',
  'peregrintook',
  'foolofatook',
  'stickeminastew',
  'ICareNot',
  'IAmNoMan',
  'Avocadorable',
  'FrostedCupcake',
  'MortysCousin',
  'MasterCheif',
  'RedMonkeyButt',
  'Dexter',
  'FreeHugz',
  'actuallythedog',
  'actuallythecat',
  'pixiedust',
  'ChopSuey',
  'turkeySandwich',
  'CourtesyFlush',
  'javascriptisdead',
  'hogwartsdropout',
  'harrypotterfan',
  'spongebob',
  'nothisispatrick',
  'CountSwagula',
  'Snax',
  'Fartoolong',
  'Loliateyourcat',
  'feedmeastraycat',
  'malus',
  'MasterWarcraft',
  'Odinson',
  'MarvelFanatic',
  'SpidermanIsGuilty',
  'PoliticalStatement',
  'Thule',
  'CthulhuReigns',
  'AverageForumUser',
  'ihazquestion',
  'thinkingaboutit',
  'Nuggz',
  'BreadPitt',
  'loveandpoprockz',
  'OmnipotentBug',
  'Mando',
  'AngelWonderland',
  'severusvape',
  'GrangerDanger',
  'HotButterPopcorn',
  'MelonSmasher',
  'morganfreeman',
  'purplelightsaber',
  'beguntheclonewars',
  'Wolverine',
  'BronyBoy',
  'RainbowSplash',
  'CrashOverride',
  'ZeroCool',
  'Bandicoot',
  'Cereal',
  'Blade',
  'Phreak',
  'thePLAGUE',
  'Nikon',
  'Razor',
  'NotACop',
  'morpheus',
  'NEO',
  'Trinity',
  'Cypher',
  'AgentSmith',
  'Switch',
  'Nintendog',
];

const stateOptions = [
  'Outside U.S.',
  'Alabama',
  'Arizona',
  'Alaska',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];

const genderOptions = [
  'Male',
  'Male',
  'Male',
  'Male',
  'Male',
  'Male',
  'Male',
  'Male',
  'Male',
  'Male',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Bigender',
  'Agender',
  'Androgyne',
  'Genderqueer',
  'Third',
  'Fourth',
  'Fluid',
  'Questioning',
  'Other',
];

const sexualityOptions = [
  'Heterosexual',
  'Heterosexual',
  'Heterosexual',
  'Heterosexual',
  'Heterosexual',
  'Heterosexual',
  'Heterosexual',
  'Heterosexual',
  'Heterosexual',
  'Homosexual',
  'Homosexual',
  'Bisexual',
  'Bisexual',
  'Queer',
  'Questioning',
  'Asexual',
  'Aromantic',
  'Pansexual',
  'Demisexual',
  'Demiromantic',
  'Polyamorous',
  'Other',
];

const educationOptions = [
  'Boot Camp Certification',
  'Boot Camp Certification',
  'Boot Camp Certification',
  'High School',
  'High School',
  'High School',
  '2-Year College',
  '2-Year College',
  '2-Year College',
  '4-Year College',
  '4-Year College',
  '4-Year College',
  'Graduate School',
  'Graduate School',
  'PhD',
];

const firstNameOptions = [
  'James',
  'Robert',
  'John',
  'Michael',
  'William',
  'David',
  'Richard',
  'Joseph',
  'Thomas',
  'Charles',
  'Christopher',
  'Daniel',
  'Matthew',
  'Anthony',
  'Keanu',
  'Brandon',
  'Eric',
  'Cody',
  'Mark',
  'Donald',
  'Steven',
  'Stephen',
  'Paul',
  'Andrew',
  'Joshua',
  'Mary',
  'Patricia',
  'Jennifer',
  'Linda',
  'Elizabeth',
  'Barbara',
  'Susan',
  'Jessica',
  'Sarah',
  'Karen',
  'Nancy',
  'Lisa',
  'Betty',
  'Margaret',
  'Sandra',
  'Ashley',
  'Kimberly',
  'Emily',
  'Donna',
  'Michelle',
  'Dorothy',
  'Olivia',
];

const lastNameOptions = [
  'Smith',
  'Johnson',
  'Williams',
  'Brown',
  'Jones',
  'Garcia',
  'Miller',
  'Davis',
  'Rodriguez',
  'Martinez',
  'Hernandez',
  'Lopez',
  'Gonzalez',
  'Wilson',
  'Anderson',
  'Thomas',
  'Taylor',
  'Moore',
  'Jackson',
  'Martin',
];

const cityOptions = [
  'Franklin',
  'Clinton',
  'Arlington',
  'Madison',
  'Centerville',
  'Lebanon',
  'Georgetown',
  'Springfield',
  'Chester',
  'Fairview',
  'Greenville',
  'Bristol',
  'Nashville',
  'Dayton',
  'Dover',
  'Madison',
  'Salem',
  'Winchester',
  'Oakland',
  'Milton',
  'Newport',
  'Ashland',
  'Bloomington',
  'Riverside',
  'Manchester',
  'Oxford',
  'Burlington',
  'Jackson',
  'Milford',
  'Clayton',
  'Kingston',
  'Auburn',
  'Lexington',
];

usernameOptions.forEach((username) => {
  userData.push({
    username,
    email: username + '@gmail.com',
    password: 'password',
    first_name:
      firstNameOptions[Math.floor(Math.random() * firstNameOptions.length)],
    last_name:
      lastNameOptions[Math.floor(Math.random() * lastNameOptions.length)],
    city: cityOptions[Math.floor(Math.random() * cityOptions.length)],
    state: stateOptions[Math.floor(Math.random() * stateOptions.length)],
    birthday: '1995-12-04',
    years_coding: Math.floor(Math.random() * 15),
    profile_image: `https://picsum.photos/500?random=${Math.floor(
      Math.random() * 100
    )}`,
    education:
      educationOptions[Math.floor(Math.random() * educationOptions.length)],
    gender_identity:
      genderOptions[Math.floor(Math.random() * genderOptions.length)],
    sexual_orientation:
      sexualityOptions[Math.floor(Math.random() * sexualityOptions.length)],
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  });
});

const seedUsers = () => User.bulkCreate(userData, { individualHooks: true });

module.exports = seedUsers;
